// Writes src/data/bestsellers.ts: ASINs ranked by units sold, from the order
// lines that atreya-aplus/orders-trend.js pulls (`node orders-trend.js 45 --items 45`).
// Cancelled orders do not count. Re-run before a release so the home page
// Bestsellers row follows what is actually selling.
// Usage: node scripts/bestsellers.mjs [path/to/orders_trend.json]
import fs from 'node:fs';

const src = process.argv[2] || 'E:/atreya/listing/atreya-aplus/orders_trend.json';
const { pulledAt, itemDays, lines } = JSON.parse(fs.readFileSync(src, 'utf8'));
if (!lines?.length) throw new Error(`${src} has no order lines; run orders-trend.js with --items`);

const units = {};
for (const l of lines) {
  if (l.status === 'Canceled') continue;
  units[l.asin] = (units[l.asin] ?? 0) + (l.qty || 0);
}
const ranked = Object.entries(units).sort((a, b) => b[1] - a[1]);

const out = `// Generated by scripts/bestsellers.mjs from Amazon order lines. Do not edit by hand.
// Window: the ${itemDays} days to ${pulledAt.slice(0, 10)}. ASINs by units sold, cancellations excluded.
// The list may hold ASINs that are not on the site (other brands in the same
// seller account); the home page only ranks what is in PRODUCTS.
export const BESTSELLERS: string[] = [
${ranked.map(([a, n]) => `  '${a}', // ${n}`).join('\n')}
];
`;
fs.writeFileSync('src/data/bestsellers.ts', out);
console.log(`wrote ${ranked.length} ASINs; top 12:`, ranked.slice(0, 12));
