// Generated by scripts/bestsellers.mjs from Amazon order lines. Do not edit by hand.
// Window: the 45 days to 2026-10-04. ASINs by units sold, cancellations excluded.
// The list may hold ASINs that are not on the site (other brands in the same
// seller account); the home page only ranks what is in PRODUCTS.
export const BESTSELLERS: string[] = [
  'B0HB4N2JSH', // 82
  'B0HDCT5CVF', // 55
  'B0HGM61K1N', // 45
  'B0HF4N37JD', // 26
  'B0HF4PXH7S', // 20
  'B0HC44WKBT', // 10
  'B0HC479QXR', // 6
  'B0HFBM7WZG', // 5
  'B0HD2H3LF4', // 2
  'B0HDCXZRNV', // 2
  'B09QJV7VXZ', // 2
  'B0HJ8KSPP7', // 2
  'B0HC4DHXNK', // 2
  'B0HFPJJSW4', // 1
  'B0HF9ZJXT3', // 1
  'B0HF9ZT32L', // 1
  'B0HJ3ZSPXN', // 1
];
