// Generated by scripts/fetch-products.mjs — do not edit by hand.
export interface Product {
  asin: string;
  name: string;
  fullName: string;
  description: string;
  category: string;
  price: number;
  mrp: number | null;
  image: string | null;
  images: string[];
  specs: { label: string; value: string }[];
  bullets: string[];
  amazonUrl: string;
}

export const CATEGORIES = ["Crochet","Festive Décor","Artificial Flowers","Home Décor","Craft Supplies"] as const;

export const PRODUCTS: Product[] = [
  {
    "asin": "B0GG5BVR7R",
    "name": "Crochet Evil Eye Hanging Charm",
    "fullName": "",
    "description": "Add a calm, classy boho accent to your space with this Atreya Handmade Crochet Evil Eye Hanging Charm (Blue). Crafted with detailed crochet work, a scalloped edge, pearl-style beads, and a soft tassel, it’s an easy way to upgrade your door/handle decor or car mirror with something handmade and unique. Traditionally, the evil eye motif is associated with protection and good vibes—this piece is best enjoyed as a beautiful decor accessory for home, car, or gifting.",
    "category": "Crochet",
    "price": 189,
    "mrp": 499,
    "image": "/products/B0GG5BVR7R.jpg",
    "images": [
      "/products/B0GG5BVR7R.jpg",
      "/products/B0GG5BVR7R_2.jpg",
      "/products/B0GG5BVR7R_3.jpg",
      "/products/B0GG5BVR7R_4.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Blue"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "1"
      },
      {
        "label": "Included Components",
        "value": "crochet"
      },
      {
        "label": "Occasion",
        "value": "Valentine's Day"
      },
      {
        "label": "Theme",
        "value": "Love"
      },
      {
        "label": "Shape",
        "value": "Round"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Handmade Crochet Evil Eye: Neatly hand-crocheted evil eye motif with a scalloped border for a premium, clean finish.",
      "Elegant Blue Palette: Deep blue + sky blue + white design that looks classy on doors, car mirrors, wardrobes, and wall hooks.",
      "Pearl Bead Detail: Finished with pearl-style beads for a minimal, aesthetic look (adds a subtle premium touch).",
      "Soft Tassel Finish: Long yarn tassel gives a traditional “latkan” feel—perfect for home decor and gifting.",
      "Multi-Use Hanging Charm: Use as door hanging, car rear-view charm, bag charm, nursery decor, or key holder accent."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0GG5BVR7R"
  },
  {
    "asin": "B0GDXXM3PR",
    "name": "Mini Crochet Hearts — Set of 12",
    "fullName": "",
    "description": "Add instant charm to your home with Atreya Mini Crochet Hearts (Set of 12). These tiny handmade yarn hearts are perfect as bowl fillers, tiered tray décor, and bookshelf styling accents. Whether you’re decorating your living room, creating a festive setup, styling gift hampers, or working on DIY crafts, these crochet hearts add a warm, cozy, handmade feel. Each heart is handcrafted with soft yarn for a textured look that photographs beautifully and elevates everyday décor. Ideal for Valentine’s décor, wedding décor, party favors, gift basket fillers, and creative projects.",
    "category": "Crochet",
    "price": 1299,
    "mrp": 1699,
    "image": "/products/B0GDXXM3PR.jpg",
    "images": [
      "/products/B0GDXXM3PR.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Mix"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Included Components",
        "value": "Gajra"
      },
      {
        "label": "Occasion",
        "value": "Christmas, Diwali, Valentine's Day, Wedding"
      },
      {
        "label": "Theme",
        "value": "Love"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "HANDMADE MINI HEARTS (SET OF 12): Atreya crochet hearts are carefully handcrafted to add a cozy, premium handmade touch to your décor and gifting.",
      "PERFECT FOR BOWL FILLERS & TRAYS: Tiny hearts (approx. 1.25 inch) are ideal for bowls, tiered trays, jars, coffee tables, bedside décor, and festive styling.",
      "MULTI-USE CRAFT DECOR: Use for DIY crafts, garlands, scrapbooking, gift wrapping, party favors, wedding décor, table scatter, and hamper styling.",
      "HANDMADE DISCLAIMER + SAFETY: Slight variations in size/shape/color are natural in handmade items. Not a toy—keep away from children under 4 and pets (small parts).",
      "🎁 Ideal for Gifting & Festive Styling"
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0GDXXM3PR"
  },
  {
    "asin": "B0GC6KJCSC",
    "name": "Mini Crochet Hearts — Set of 6 (Multicolor)",
    "fullName": "",
    "description": "Add a small touch of love to your decor with Atreya Mini Crochet Hearts. This set of 6 handcrafted hearts is designed to be styled effortlessly—scatter them in a decorative bowl, add them to a vase arrangement, place them on a tiered tray, or use them as gift hamper fillers. Each piece is handmade, making every set slightly unique.",
    "category": "Crochet",
    "price": 699,
    "mrp": 999,
    "image": "/products/B0GC6KJCSC.jpg",
    "images": [
      "/products/B0GC6KJCSC.jpg",
      "/products/B0GC6KJCSC_2.jpg",
      "/products/B0GC6KJCSC_3.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Red"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Included Components",
        "value": "Hearts"
      },
      {
        "label": "Occasion",
        "value": "Christmas, Diwali, Valentine's Day, Wedding"
      },
      {
        "label": "Theme",
        "value": "Love"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Handmade, artisan-crafted: Each mini heart is individually crocheted for a charming, handmade finish.",
      "Curated multicolor set: A balanced mix of colors that adds a cozy, romantic accent to any space.",
      "Easy home styling: Use as bowl filler, vase filler, tiered tray decor, shelf styling, hamper filler, or craft embellishments.",
      "Size & pack details: Set of 6 mini crochet hearts. Each heart is approx. 1.25 inches (handmade sizing may vary slightly)."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0GC6KJCSC"
  },
  {
    "asin": "B0G95YC1T9",
    "name": "Crochet Heart Ornaments — Set of 12 (Red)",
    "fullName": "",
    "description": "Bring a cozy, handmade touch to your décor with Atreya Crochet Heart Ornaments. This set includes 12 adorable yarn hearts in red — easy to hang, easy to style, and perfect for creating a warm “love” atmosphere at home. Use them as hanging ornaments for windows, décor trees, wall garlands, mirror corners, gift wrapping accents, or photo backdrops. They also look beautiful as bowl/vase fillers or in gift hampers. Whether you’re decorating for Valentine’s Day, an anniversary dinner, a wedding function, or an engagement party, these hearts add a soft, thoughtful charm that feels personal.",
    "category": "Crochet",
    "price": 1299,
    "mrp": 1699,
    "image": "/products/B0G95YC1T9.jpg",
    "images": [
      "/products/B0G95YC1T9.jpg",
      "/products/B0G95YC1T9_2.jpg",
      "/products/B0G95YC1T9_3.jpg",
      "/products/B0G95YC1T9_4.jpg",
      "/products/B0G95YC1T9_5.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Red"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "12"
      },
      {
        "label": "Included Components",
        "value": "Hearts"
      },
      {
        "label": "Occasion",
        "value": "Christmas, Diwali, Valentine's Day, Wedding"
      },
      {
        "label": "Theme",
        "value": "Love"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "1. Value Pack for Instant Decor Set of 12 crochet heart ornaments in a charming red, pink & white mix — perfect for quick festive styling and craft projects.",
      "2. Perfect Mini Size (Looks Cute Everywhere) Each heart is approx 6.5 × 5.5 cm (2.56 × 2.17 in) — ideal for small corners, centrepieces, hampers, jars, baskets, and hanging décor",
      "3. Ready to Hang + Easy to Style Comes with rope/loop for hanging — decorate trees, windows, mirrors, gift wraps, garlands, photo walls, or use as table accents",
      "4. Handcrafted Look, Soft & Lightweight Finely crocheted with a neat, dense texture and a soft feel — lightweight pieces that add warmth and a handmade vibe to your space",
      "5. Made for Love-Themed Moments Great for Valentine’s Day, anniversaries, engagements, weddings, party décor, return gifts, and romantic room styling."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0G95YC1T9"
  },
  {
    "asin": "B0GDY7RSXY",
    "name": "Crochet Cherry Keychain",
    "fullName": "",
    "description": "Add a touch of charm to your everyday essentials with the ATREYA Handmade Crochet Cherry Keychain. Beautifully hand-crocheted using soft, durable yarn, this cute cherry design makes a perfect accessory for keys, handbags, backpacks, or pouches. Designed with care and creativity, this keychain reflects ATREYA’s love for handmade craftsmanship and aesthetic details. Each piece is unique, making it a thoughtful gift for yourself or your loved ones. 🎁 Perfect For Keys, handbags, backpacks & pouches Handmade gift lovers Birthday gifts & hampers Return gifts & party favors Cute aesthetic accessories",
    "category": "Crochet",
    "price": 199,
    "mrp": 499,
    "image": "/products/B0GDY7RSXY.jpg",
    "images": [
      "/products/B0GDY7RSXY.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Red, Green"
      },
      {
        "label": "Item Weight",
        "value": "15 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "1"
      },
      {
        "label": "Included Components",
        "value": "1 Keychain With Heart Charm And Flower Decoration, 1 Metal Key Ring, 1 Chain Connector"
      },
      {
        "label": "Theme",
        "value": "Heart, Flower, Love, Valentine, Romantic, Handmade, Cute, Kawaii"
      },
      {
        "label": "Pattern",
        "value": "Fruit"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [],
    "amazonUrl": "https://www.amazon.in/dp/B0GDY7RSXY"
  },
  {
    "asin": "B0GDY4D9FN",
    "name": "Crochet Heart Keychain with Flower",
    "fullName": "",
    "description": "This charming handmade crochet keychain from Atreya brings a delightful touch of handcrafted artistry to your everyday essentials. Featuring a vibrant red heart paired with a delicate white flower with a cheerful yellow centre, this adorable accessory adds personality and warmth to your keys, bags, or backpack. Each piece is carefully crocheted by hand, making every keychain unique with its own character and charm. The soft yet durable yarn construction ensures this keychain can withstand daily use whilst maintaining its eye-catching appeal. The sturdy metal keyring attachment provides secure fastening to keep your keys safe. Perfect as a thoughtful gift for loved ones or as a sweet treat for yourself, this crochet heart keychain combines functionality with whimsical design. Its compact size makes it easy to carry without adding bulk, whilst the bright red colour ensures you can spot your keys quickly. Whether you're looking to add a handmade touch to your accessories or searching for a heartfelt gift, this crochet keychain delivers both style and practicality in one adorable package.",
    "category": "Crochet",
    "price": 299,
    "mrp": 499,
    "image": "/products/B0GDY4D9FN.jpg",
    "images": [
      "/products/B0GDY4D9FN.jpg",
      "/products/B0GDY4D9FN_2.jpg",
      "/products/B0GDY4D9FN_3.jpg",
      "/products/B0GDY4D9FN_4.jpg",
      "/products/B0GDY4D9FN_5.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Red, White, Yellow"
      },
      {
        "label": "Item Weight",
        "value": "15 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "1"
      },
      {
        "label": "Included Components",
        "value": "1 Keychain With Heart Charm And Flower Decoration, 1 Metal Key Ring, 1 Chain Connector"
      },
      {
        "label": "Theme",
        "value": "Heart, Flower, Love, Valentine, Romantic, Handmade, Cute, Kawaii"
      },
      {
        "label": "Pattern",
        "value": "Crochet Textured Heart With Daisy Flower"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [],
    "amazonUrl": "https://www.amazon.in/dp/B0GDY4D9FN"
  },
  {
    "asin": "B0GDV4HTRJ",
    "name": "Crochet Rose Gajra / Hair Parandi (Pair)",
    "fullName": "",
    "description": "Add a touch of timeless elegance to your traditional look with this handcrafted crochet rose gajra. Made with love and care, this floral accessory features soft white crochet loops paired with vibrant red rose flowers, giving the charm of real flowers with the durability of handmade yarn. Perfect for braids, buns, or parandi-style hairstyles, this reusable gajra stays fresh forever and is gentle on hair and skin. Whether you’re dressing up for a wedding, festival, pooja, or classical dance, this crochet gajra adds grace and tradition to your look.",
    "category": "Crochet",
    "price": 499,
    "mrp": 999,
    "image": "/products/B0GDV4HTRJ.jpg",
    "images": [
      "/products/B0GDV4HTRJ.jpg",
      "/products/B0GDV4HTRJ_2.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "White"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Included Components",
        "value": "Gajra"
      },
      {
        "label": "Occasion",
        "value": "Christmas, Diwali, Valentine's Day, Wedding"
      },
      {
        "label": "Theme",
        "value": "Love"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "🌹 100% Handmade Crochet Work",
      "🌼 Soft & Skin-Friendly Yarn",
      "♻️ Reusable – No Wilting, No Mess",
      "💃 Lightweight & Comfortable to Wea",
      "🎁 Ideal for Gifting & Festive Styling"
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0GDV4HTRJ"
  },
  {
    "asin": "B0GDY833NN",
    "name": "Crochet Popcorn-Stitch Scrunchie",
    "fullName": "",
    "description": "This charming handmade crochet scrunchie from Atreya brings a delightful pop of colour to your everyday style. Featuring a playful popcorn stitch design in soft pastel teal and pink, this hair tie combines cottagecore aesthetics with practical functionality. The textured bobble detailing creates a dimensional flower-like appearance that adds personality to any hairstyle, whether you're styling a messy bun, ponytail, or half-up look. Crafted with care using gentle yarn, this scrunchie is soft on your hair and helps prevent breakage and creasing compared to traditional elastic bands. The comfortable stretch ensures a secure hold without pulling or tugging, making it suitable for all hair types and thicknesses. This cute hair accessory works beautifully for casual outings, work, or special occasions. It also makes a thoughtful gift for friends, sisters, or anyone who appreciates handcrafted accessories with a vintage-inspired charm. Add this sweet teal and pink scrunchie to your collection and embrace the whimsical beauty of handmade fashion accessories.",
    "category": "Crochet",
    "price": 199,
    "mrp": null,
    "image": "/products/B0GDY833NN.jpg",
    "images": [
      "/products/B0GDY833NN.jpg",
      "/products/B0GDY833NN_2.jpg",
      "/products/B0GDY833NN_3.jpg",
      "/products/B0GDY833NN_4.jpg"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Acrylic Yarn, Cotton Yarn"
      },
      {
        "label": "Item Weight",
        "value": "5 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "1"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "HANDMADE CROCHET DESIGN: Atreya scrunchie features charming popcorn stitch bobbles in a delightful teal and pink colour combination, handcrafted with care for a unique cottagecore aesthetic",
      "SOFT AND GENTLE: Made with soft yarn material that is gentle on hair, preventing breakage and damage while providing a secure yet comfortable hold for all hair types",
      "VERSATILE HAIR ACCESSORY: Perfect for ponytails, buns, and half-up hairstyles, this pastel scrunchie adds a cute and playful touch to everyday looks or special occasions",
      "THOUGHTFUL GIFT IDEA: Makes a lovely gift for her, whether for birthdays, celebrations, or just because - a sweet handmade accessory that shows care and attention to detail",
      "DURABLE CONSTRUCTION: Carefully crocheted with quality yarn to ensure long-lasting wear, maintaining its shape and vibrant colours through regular use"
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0GDY833NN"
  },
  {
    "asin": "B0B8XR4XNW",
    "name": "Silver Hanging Bells — 2.5\" (Pack of 48)",
    "fullName": "",
    "description": "Silver Decorative Plastic Bells By Atreya, Perfect for Party, Event, Birthday Decoration Note : Objects in images may appear smaller or larger than real. Kindly refer the dimensions carefully to get the suitable size for you. You can check the dimensions with any scale/inch-tape available to you to understand the size of the product after checking the dimension from here.",
    "category": "Festive Décor",
    "price": 549,
    "mrp": 699,
    "image": "/products/B0B8XR4XNW.jpg",
    "images": [
      "/products/B0B8XR4XNW.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Silver"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "12"
      },
      {
        "label": "Included Components",
        "value": "Bells"
      },
      {
        "label": "Occasion",
        "value": "Birthday, Christmas, Wedding"
      },
      {
        "label": "Theme",
        "value": "Religious"
      },
      {
        "label": "Shape",
        "value": "Bell"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Silver Colored Plastic Bells for Crafts/Decoration/Festive Decor",
      "Ideal for home Decoration, Temple Decoration, Christmas celebration",
      "The embossed designs may vary.",
      "Important : THESE BELLS ARE FOR HANGING PURPOSE ONLY. IT DOESN'T RING."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0B8XR4XNW"
  },
  {
    "asin": "B0B8XRDHPW",
    "name": "Silver Hanging Bells — 2.5\" (Pack of 12)",
    "fullName": "",
    "description": "Silver Decorative Plastic Bells By Atreya, Perfect for Party, Event, Birthday Decoration Note : Objects in images may appear smaller or larger than real. Kindly refer the dimensions carefully to get the suitable size for you. You can check the dimensions with any scale/inch-tape available to you to understand the size of the product after checking the dimension from here.",
    "category": "Festive Décor",
    "price": 189,
    "mrp": 699,
    "image": "/products/B0B8XRDHPW.jpg",
    "images": [
      "/products/B0B8XRDHPW.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Silver"
      },
      {
        "label": "Item Weight",
        "value": "500 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "12"
      },
      {
        "label": "Included Components",
        "value": "Bells"
      },
      {
        "label": "Occasion",
        "value": "Birthday, Christmas, Wedding"
      },
      {
        "label": "Theme",
        "value": "Religious"
      },
      {
        "label": "Shape",
        "value": "Bell"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Silver Colored Plastic Bells for Crafts/Decoration/Festive Decor",
      "Ideal for home Decoration, Temple Decoration, Christmas celebration",
      "The embossed designs may vary.",
      "Important : THESE BELLS ARE FOR HANGING PURPOSE ONLY. IT DOESN'T RING."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0B8XRDHPW"
  },
  {
    "asin": "B09QJVDNFW",
    "name": "Golden Jingle Bells — 2.5\" (Pack of 48)",
    "fullName": "",
    "description": "",
    "category": "Festive Décor",
    "price": 529,
    "mrp": 1299,
    "image": "/products/B09QJVDNFW.jpg",
    "images": [
      "/products/B09QJVDNFW.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "gold"
      },
      {
        "label": "Item Weight",
        "value": "0.15 Pounds"
      },
      {
        "label": "Number of Pieces",
        "value": "48"
      },
      {
        "label": "Included Components",
        "value": "Plastic Bells"
      },
      {
        "label": "Occasion",
        "value": "Birthday, Christmas, Wedding"
      },
      {
        "label": "Theme",
        "value": "Religious"
      },
      {
        "label": "Shape",
        "value": "Bell"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Golden Colored Plastic Bells for Crafts/Decoration/Festive Decor",
      "Ideal for home Decoration, Temple Decoration, Christmas celebration",
      "The embossed designs may vary.",
      "Important : THESE BELLS ARE FOR HANGING PURPOSE ONLY. IT DOESN'T RING."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B09QJVDNFW"
  },
  {
    "asin": "B09QJV7VXZ",
    "name": "Golden Jingle Bells — 2.5\" (Pack of 24)",
    "fullName": "",
    "description": "Light Golden Decorative Plastic Bells By Atreya, Perfect for Party, Event, Birthday Decoration Note : Objects in images may appear smaller or larger than real. Kindly refer the dimensions carefully to get the suitable size for you. You can check the dimensions with any scale/inch-tape available to you to understand the size of the product after checking the dimension from here.",
    "category": "Festive Décor",
    "price": 499,
    "mrp": 1299,
    "image": "/products/B09QJV7VXZ.jpg",
    "images": [
      "/products/B09QJV7VXZ.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "gold"
      },
      {
        "label": "Item Weight",
        "value": "0.15 Pounds"
      },
      {
        "label": "Number of Pieces",
        "value": "24"
      },
      {
        "label": "Included Components",
        "value": "Plastic Bells"
      },
      {
        "label": "Occasion",
        "value": "Birthday, Christmas, Wedding"
      },
      {
        "label": "Theme",
        "value": "Religious"
      },
      {
        "label": "Shape",
        "value": "Spherical"
      },
      {
        "label": "Mounting Type",
        "value": "Hanging"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Golden Colored Plastic Bells for Crafts/Decoration/Festive Decor",
      "Ideal for home Decoration, Temple Decoration, Christmas celebration",
      "The embossed designs may vary.",
      "Important : THESE BELLS ARE FOR HANGING PURPOSE ONLY. IT DOESN'T RING."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B09QJV7VXZ"
  },
  {
    "asin": "B09Y2B4XHL",
    "name": "Jasmine Door Toran — Set of 4",
    "fullName": "",
    "description": "Beautiful Handmade Jasmine Floral Petals Torans for Used for Home Decor, Wedding Decoration, Mehendi/Haldi Party, Venue Decoration, Special Event Decoration, Perfect for Diwali Gift.",
    "category": "Festive Décor",
    "price": 399,
    "mrp": 1499,
    "image": "/products/B09Y2B4XHL.jpg",
    "images": [
      "/products/B09Y2B4XHL.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "White and golden"
      },
      {
        "label": "Included Components",
        "value": "garland"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Set of 4 Faux Jasmine Floral Petals with Plastic Bell",
      "Length - 39 inches/100 cm drop of Hanging Garland with bell",
      "Used for Home Decor, Wedding Decoration, Mehendi/Haldi Party, Venue Decoration, Special Event Decoration, Perfect for Diwali Gift.",
      "Material : Faux Plastic Jasmine Petals. Gold Painted Bell, White Artificial Jasmine, Mild Jasmine Fragrance",
      "Note : Please be advised that colours may vary in the photos advertised."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B09Y2B4XHL"
  },
  {
    "asin": "B0CMDJR8QM",
    "name": "Eternal Love Rose Bouquet (Red)",
    "fullName": "",
    "description": "Celebrate timeless affection with Atreya's Eternal Love bouquet. Meticulously crafted to echo the heartbeats of Indian romance, these artificial roses offer a touch of traditional elegance and charm, seamlessly blending with the rich tapestry of our Indian homes.",
    "category": "Artificial Flowers",
    "price": 149,
    "mrp": 599,
    "image": "/products/B0CMDJR8QM.jpg",
    "images": [
      "/products/B0CMDJR8QM.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Red"
      },
      {
        "label": "Included Components",
        "value": "Arrangement Accessories"
      },
      {
        "label": "Occasion",
        "value": "Wedding"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Desi Realism: Every petal, every shade crafted keeping the Indian aesthetics in mind. Feel the lush beauty of a real rose in every glance and touch.",
      "Premium Quality: Made using top-notch material that not only look authentic but also provide a soft, natural feel.",
      "Everlasting Beauty: Bypass the worries of natural roses wilting in our tropical climate. Atreya's roses remain vibrant and fresh throughout the seasons.",
      "Perfect for Indian Festivities: From Diwali puja setups to wedding house decorations or simply elevating the charm of your drawing room, these roses resonate with every occasion.",
      "Number of Flowers: Contains 12 individual flowers crafted to perfection."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0CMDJR8QM"
  },
  {
    "asin": "B0CMDK5J4T",
    "name": "Eternal Love Rose Bouquet (Pink)",
    "fullName": "",
    "description": "Celebrate timeless affection with Atreya's Eternal Love bouquet. Meticulously crafted to echo the heartbeats of Indian romance, these artificial roses offer a touch of traditional elegance and charm, seamlessly blending with the rich tapestry of our Indian homes.",
    "category": "Artificial Flowers",
    "price": 149,
    "mrp": 599,
    "image": "/products/B0CMDK5J4T.jpg",
    "images": [
      "/products/B0CMDK5J4T.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Pink"
      },
      {
        "label": "Included Components",
        "value": "Arrangement Accessories"
      },
      {
        "label": "Occasion",
        "value": "Wedding"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Desi Realism: Every petal, every shade crafted keeping the Indian aesthetics in mind. Feel the lush beauty of a real rose in every glance and touch.",
      "Premium Quality: Made using top-notch material that not only look authentic but also provide a soft, natural feel.",
      "Everlasting Beauty: Bypass the worries of natural roses wilting in our tropical climate. Atreya's roses remain vibrant and fresh throughout the seasons.",
      "Perfect for Indian Festivities: From Diwali puja setups to wedding house decorations or simply elevating the charm of your drawing room, these roses resonate with every occasion.",
      "Number of Flowers: Contains 12 individual flowers crafted to perfection."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0CMDK5J4T"
  },
  {
    "asin": "B0CMDJBYZ4",
    "name": "Eternal Love Rose Bouquet (Yellow)",
    "fullName": "",
    "description": "Celebrate timeless affection with Atreya's Eternal Love bouquet. Meticulously crafted to echo the heartbeats of Indian romance, these artificial roses offer a touch of traditional elegance and charm, seamlessly blending with the rich tapestry of our Indian homes.",
    "category": "Artificial Flowers",
    "price": 149,
    "mrp": 599,
    "image": "/products/B0CMDJBYZ4.jpg",
    "images": [
      "/products/B0CMDJBYZ4.jpg",
      "/products/B0CMDJBYZ4_2.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Yellow"
      },
      {
        "label": "Included Components",
        "value": "Arrangement Accessories"
      },
      {
        "label": "Occasion",
        "value": "Wedding"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Desi Realism: Every petal, every shade crafted keeping the Indian aesthetics in mind. Feel the lush beauty of a real rose in every glance and touch.",
      "Premium Quality: Made using top-notch material that not only look authentic but also provide a soft, natural feel.",
      "Everlasting Beauty: Bypass the worries of natural roses wilting in our tropical climate. Atreya's roses remain vibrant and fresh throughout the seasons.",
      "Perfect for Indian Festivities: From Diwali puja setups to wedding house decorations or simply elevating the charm of your drawing room, these roses resonate with every occasion.",
      "Number of Flowers: Contains 12 individual flowers crafted to perfection."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0CMDJBYZ4"
  },
  {
    "asin": "B09Y3J9PSQ",
    "name": "Sunflower Heads — Pack of 20",
    "fullName": "",
    "description": "These adorable artificial SUNFLOWERS are perfect for crafting flower crowns and all kinds of floral accessories. They are decorative flowers and permanent botanical beauty!",
    "category": "Artificial Flowers",
    "price": 399,
    "mrp": 1499,
    "image": "/products/B09Y3J9PSQ.jpg",
    "images": [
      "/products/B09Y3J9PSQ.jpg",
      "/products/B09Y3J9PSQ_2.jpg",
      "/products/B09Y3J9PSQ_3.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Orange"
      },
      {
        "label": "Included Components",
        "value": "20 Sunflower Heads"
      },
      {
        "label": "Occasion",
        "value": "Wedding"
      }
    ],
    "bullets": [
      "Artificial silk, textile, wax flowers may be used for bridal bouquets and wedding accessories, home decoration, vase arrangement or DIY.",
      "Colors: yellow - orange and dark brown pistil",
      "Each flower has approximately: 10 cm in diameter",
      "Material: fabric, plastic",
      "Pack of 20"
    ],
    "amazonUrl": "https://www.amazon.in/dp/B09Y3J9PSQ"
  },
  {
    "asin": "B0GDY75WHT",
    "name": "Wooden Floor Vase with Brass Work",
    "fullName": "",
    "description": "Add timeless elegance to your living space with this Atreya handcrafted wooden decorative vase, beautifully adorned with intricate brass floral motifs and detailed hand carving. The rich antique brown finish paired with golden brass accents creates a royal, ethnic look that instantly elevates any interior. Perfect as a floor vase, console décor, or statement centerpiece, this tall vase blends traditional craftsmanship with modern home styling.",
    "category": "Home Décor",
    "price": 2699,
    "mrp": 4999,
    "image": "/products/B0GDY75WHT.jpg",
    "images": [
      "/products/B0GDY75WHT.jpg",
      "/products/B0GDY75WHT_2.jpg",
      "/products/B0GDY75WHT_3.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Brown"
      },
      {
        "label": "Item Weight",
        "value": "2 Kilograms"
      },
      {
        "label": "Number of Pieces",
        "value": "1"
      },
      {
        "label": "Occasion",
        "value": "Engagement, New Year, Valentine's Day, Wedding"
      },
      {
        "label": "Theme",
        "value": "Flowers"
      },
      {
        "label": "Shape",
        "value": "Pot"
      },
      {
        "label": "Pattern",
        "value": "Floral"
      },
      {
        "label": "Room Type",
        "value": "Bedroom, Dining Room, Home Office, Living Room"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "Handcrafted Excellence – Detailed hand carving with embedded brass leaf motifs",
      "Antique Finish – Rich brown tone with golden highlights for a luxurious look",
      "Premium Solid Wood – Made from high-quality seasoned wood for durability",
      "Versatile Décor – Ideal for living rooms, bedrooms, offices, hotels & lobbies",
      "Standalone Showpiece – Looks stunning with or without artificial flowers"
    ],
    "amazonUrl": "https://www.amazon.in/dp/B0GDY75WHT"
  },
  {
    "asin": "B09Y29QS4V",
    "name": "White Pearl Beads 6mm — 1000 pcs",
    "fullName": "",
    "description": "6mm ivory pearl beads, 1.5mm hole for jewellery, flower sprays, vines and DIY & wedding craft. Faux/Acrylic/plastic beads For jewelry, wedding lace/dress embellishment, framing and all kinds of craft.",
    "category": "Craft Supplies",
    "price": 199,
    "mrp": 799,
    "image": "/products/B09Y29QS4V.jpg",
    "images": [
      "/products/B09Y29QS4V.jpg"
    ],
    "specs": [
      {
        "label": "Colour",
        "value": "Ivory, White"
      },
      {
        "label": "Item Weight",
        "value": "100 Grams"
      },
      {
        "label": "Number of Pieces",
        "value": "1000"
      },
      {
        "label": "Shape",
        "value": "Round,Flower"
      },
      {
        "label": "Country of Origin",
        "value": "India"
      }
    ],
    "bullets": [
      "White Pearls Beads- Round Shape",
      "QTY - 1000 Pieces , 100 Gram",
      "Materials: Plastic & Resin",
      "Bead size: 6 millimetres",
      "Bead hole size: 1.5 millimetres",
      "For jewelry, wedding lace/dress embellishment, framing and all kinds of craft."
    ],
    "amazonUrl": "https://www.amazon.in/dp/B09Y29QS4V"
  }
];
