// Generated by scripts/fetch-products.mjs — do not edit by hand.
export interface Product {
  asin: string;
  name: string;
  fullName: string;
  description: string;
  category: string;
  price: number;
  mrp: number | null;
  image: string | null;
  amazonUrl: string;
}

export const CATEGORIES = ["Crochet","Festive Décor","Artificial Flowers","Home Décor","Craft Supplies"] as const;

export const PRODUCTS: Product[] = [
  {
    "asin": "B0GG5BVR7R",
    "name": "Crochet Evil Eye Hanging Charm",
    "fullName": "",
    "description": "Add a calm, classy boho accent to your space with this Atreya Handmade Crochet Evil Eye Hanging Charm (Blue). Crafted with detailed crochet work, a scalloped edge, pearl-style beads, and a soft tassel, it’s an easy way to upgrade your door/handle decor or car mirror with something handmade and unique. Traditionally, the evil eye motif is associated with protection and good vibes—this piece is best enjoyed as a beautiful decor accessory for home, car, or gifting.",
    "category": "Crochet",
    "price": 189,
    "mrp": 499,
    "image": "/products/B0GG5BVR7R.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GG5BVR7R"
  },
  {
    "asin": "B0GDXXM3PR",
    "name": "Mini Crochet Hearts — Set of 12",
    "fullName": "",
    "description": "Add instant charm to your home with Atreya Mini Crochet Hearts (Set of 12). These tiny handmade yarn hearts are perfect as bowl fillers, tiered tray décor, and bookshelf styling accents. Whether you’re decorating your living room, creating a festive setup, styling gift hampers, or working on DIY crafts, these crochet hearts add a warm, cozy, handmade feel. Each heart is handcrafted with soft yarn for a textured look that photographs beautifully and elevates everyday décor. Ideal for Valentine’s décor, wedding décor, party favors, gift basket fillers, and creative projects.",
    "category": "Crochet",
    "price": 1299,
    "mrp": 1699,
    "image": "/products/B0GDXXM3PR.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GDXXM3PR"
  },
  {
    "asin": "B0GC6KJCSC",
    "name": "Mini Crochet Hearts — Set of 6 (Multicolor)",
    "fullName": "",
    "description": "Add a small touch of love to your decor with Atreya Mini Crochet Hearts. This set of 6 handcrafted hearts is designed to be styled effortlessly—scatter them in a decorative bowl, add them to a vase arrangement, place them on a tiered tray, or use them as gift hamper fillers. Each piece is handmade, making every set slightly unique.",
    "category": "Crochet",
    "price": 699,
    "mrp": 999,
    "image": "/products/B0GC6KJCSC.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GC6KJCSC"
  },
  {
    "asin": "B0G95YC1T9",
    "name": "Crochet Heart Ornaments — Set of 12 (Red)",
    "fullName": "",
    "description": "Bring a cozy, handmade touch to your décor with Atreya Crochet Heart Ornaments. This set includes 12 adorable yarn hearts in red — easy to hang, easy to style, and perfect for creating a warm “love” atmosphere at home. Use them as hanging ornaments for windows, décor trees, wall garlands, mirror corners, gift wrapping accents, or photo backdrops. They also look beautiful as bowl/vase fillers or in gift hampers. Whether you’re decorating for Valentine’s Day, an anniversary dinner, a wedding function, or an engagement party, these hearts add a soft, thoughtful charm that feels personal.",
    "category": "Crochet",
    "price": 1299,
    "mrp": 1699,
    "image": "/products/B0G95YC1T9.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0G95YC1T9"
  },
  {
    "asin": "B0GDY7RSXY",
    "name": "Crochet Cherry Keychain",
    "fullName": "",
    "description": "Add a touch of charm to your everyday essentials with the ATREYA Handmade Crochet Cherry Keychain. Beautifully hand-crocheted using soft, durable yarn, this cute cherry design makes a perfect accessory for keys, handbags, backpacks, or pouches. Designed with care and creativity, this keychain reflects ATREYA’s love for handmade craftsmanship and aesthetic details. Each piece is unique, making it a thoughtful gift for yourself or your loved ones. 🎁 Perfect For Keys, handbags, backpacks & pouches Handmade gift lovers Birthday gifts & hampers Return gifts & party favors Cute aesthetic accessories",
    "category": "Crochet",
    "price": 199,
    "mrp": 499,
    "image": "/products/B0GDY7RSXY.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GDY7RSXY"
  },
  {
    "asin": "B0GDY4D9FN",
    "name": "Crochet Heart Keychain with Flower",
    "fullName": "",
    "description": "This charming handmade crochet keychain from Atreya brings a delightful touch of handcrafted artistry to your everyday essentials. Featuring a vibrant red heart paired with a delicate white flower with a cheerful yellow centre, this adorable accessory adds personality and warmth to your keys, bags, or backpack. Each piece is carefully crocheted by hand, making every keychain unique with its own character and charm. The soft yet durable yarn construction ensures this keychain can withstand daily use whilst maintaining its eye-catching appeal. The sturdy metal keyring attachment provides secure fastening to keep your keys safe. Perfect as a thoughtful gift for loved ones or as a sweet treat for yourself, this crochet heart keychain combines functionality with whimsical design. Its compact size makes it easy to carry without adding bulk, whilst the bright red colour ensures you can spot your keys quickly. Whether you're looking to add a handmade touch to your accessories or searching for a heartfelt gift, this crochet keychain delivers both style and practicality in one adorable package.",
    "category": "Crochet",
    "price": 299,
    "mrp": 499,
    "image": "/products/B0GDY4D9FN.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GDY4D9FN"
  },
  {
    "asin": "B0GDV4HTRJ",
    "name": "Crochet Rose Gajra / Hair Parandi (Pair)",
    "fullName": "",
    "description": "Add a touch of timeless elegance to your traditional look with this handcrafted crochet rose gajra. Made with love and care, this floral accessory features soft white crochet loops paired with vibrant red rose flowers, giving the charm of real flowers with the durability of handmade yarn. Perfect for braids, buns, or parandi-style hairstyles, this reusable gajra stays fresh forever and is gentle on hair and skin. Whether you’re dressing up for a wedding, festival, pooja, or classical dance, this crochet gajra adds grace and tradition to your look.",
    "category": "Crochet",
    "price": 499,
    "mrp": 999,
    "image": "/products/B0GDV4HTRJ.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GDV4HTRJ"
  },
  {
    "asin": "B0GDY833NN",
    "name": "Crochet Popcorn-Stitch Scrunchie",
    "fullName": "",
    "description": "This charming handmade crochet scrunchie from Atreya brings a delightful pop of colour to your everyday style. Featuring a playful popcorn stitch design in soft pastel teal and pink, this hair tie combines cottagecore aesthetics with practical functionality. The textured bobble detailing creates a dimensional flower-like appearance that adds personality to any hairstyle, whether you're styling a messy bun, ponytail, or half-up look. Crafted with care using gentle yarn, this scrunchie is soft on your hair and helps prevent breakage and creasing compared to traditional elastic bands. The comfortable stretch ensures a secure hold without pulling or tugging, making it suitable for all hair types and thicknesses. This cute hair accessory works beautifully for casual outings, work, or special occasions. It also makes a thoughtful gift for friends, sisters, or anyone who appreciates handcrafted accessories with a vintage-inspired charm. Add this sweet teal and pink scrunchie to your collection and embrace the whimsical beauty of handmade fashion accessories.",
    "category": "Crochet",
    "price": 199,
    "mrp": null,
    "image": "/products/B0GDY833NN.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GDY833NN"
  },
  {
    "asin": "B0B8XR4XNW",
    "name": "Silver Hanging Bells — 2.5\" (Pack of 48)",
    "fullName": "",
    "description": "Silver Decorative Plastic Bells By Atreya, Perfect for Party, Event, Birthday Decoration Note : Objects in images may appear smaller or larger than real. Kindly refer the dimensions carefully to get the suitable size for you. You can check the dimensions with any scale/inch-tape available to you to understand the size of the product after checking the dimension from here.",
    "category": "Festive Décor",
    "price": 549,
    "mrp": 699,
    "image": "/products/B0B8XR4XNW.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0B8XR4XNW"
  },
  {
    "asin": "B0B8XRDHPW",
    "name": "Silver Hanging Bells — 2.5\" (Pack of 12)",
    "fullName": "",
    "description": "Silver Decorative Plastic Bells By Atreya, Perfect for Party, Event, Birthday Decoration Note : Objects in images may appear smaller or larger than real. Kindly refer the dimensions carefully to get the suitable size for you. You can check the dimensions with any scale/inch-tape available to you to understand the size of the product after checking the dimension from here.",
    "category": "Festive Décor",
    "price": 189,
    "mrp": 699,
    "image": "/products/B0B8XRDHPW.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0B8XRDHPW"
  },
  {
    "asin": "B09QJVDNFW",
    "name": "Golden Jingle Bells — 2.5\" (Pack of 48)",
    "fullName": "",
    "description": "",
    "category": "Festive Décor",
    "price": 529,
    "mrp": 1299,
    "image": "/products/B09QJVDNFW.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B09QJVDNFW"
  },
  {
    "asin": "B09QJV7VXZ",
    "name": "Golden Jingle Bells — 2.5\" (Pack of 24)",
    "fullName": "",
    "description": "Light Golden Decorative Plastic Bells By Atreya, Perfect for Party, Event, Birthday Decoration Note : Objects in images may appear smaller or larger than real. Kindly refer the dimensions carefully to get the suitable size for you. You can check the dimensions with any scale/inch-tape available to you to understand the size of the product after checking the dimension from here.",
    "category": "Festive Décor",
    "price": 499,
    "mrp": 1299,
    "image": "/products/B09QJV7VXZ.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B09QJV7VXZ"
  },
  {
    "asin": "B09Y2B4XHL",
    "name": "Jasmine Door Toran — Set of 4",
    "fullName": "",
    "description": "Beautiful Handmade Jasmine Floral Petals Torans for Used for Home Decor, Wedding Decoration, Mehendi/Haldi Party, Venue Decoration, Special Event Decoration, Perfect for Diwali Gift.",
    "category": "Festive Décor",
    "price": 399,
    "mrp": 1499,
    "image": "/products/B09Y2B4XHL.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B09Y2B4XHL"
  },
  {
    "asin": "B0CMDJR8QM",
    "name": "Eternal Love Rose Bouquet (Red)",
    "fullName": "",
    "description": "Celebrate timeless affection with Atreya's Eternal Love bouquet. Meticulously crafted to echo the heartbeats of Indian romance, these artificial roses offer a touch of traditional elegance and charm, seamlessly blending with the rich tapestry of our Indian homes.",
    "category": "Artificial Flowers",
    "price": 149,
    "mrp": 599,
    "image": "/products/B0CMDJR8QM.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0CMDJR8QM"
  },
  {
    "asin": "B0CMDK5J4T",
    "name": "Eternal Love Rose Bouquet (Pink)",
    "fullName": "",
    "description": "Celebrate timeless affection with Atreya's Eternal Love bouquet. Meticulously crafted to echo the heartbeats of Indian romance, these artificial roses offer a touch of traditional elegance and charm, seamlessly blending with the rich tapestry of our Indian homes.",
    "category": "Artificial Flowers",
    "price": 149,
    "mrp": 599,
    "image": "/products/B0CMDK5J4T.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0CMDK5J4T"
  },
  {
    "asin": "B0CMDJBYZ4",
    "name": "Eternal Love Rose Bouquet (Yellow)",
    "fullName": "",
    "description": "Celebrate timeless affection with Atreya's Eternal Love bouquet. Meticulously crafted to echo the heartbeats of Indian romance, these artificial roses offer a touch of traditional elegance and charm, seamlessly blending with the rich tapestry of our Indian homes.",
    "category": "Artificial Flowers",
    "price": 149,
    "mrp": 599,
    "image": "/products/B0CMDJBYZ4.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0CMDJBYZ4"
  },
  {
    "asin": "B09Y3J9PSQ",
    "name": "Sunflower Heads — Pack of 20",
    "fullName": "",
    "description": "These adorable artificial SUNFLOWERS are perfect for crafting flower crowns and all kinds of floral accessories. They are decorative flowers and permanent botanical beauty!",
    "category": "Artificial Flowers",
    "price": 399,
    "mrp": 1499,
    "image": "/products/B09Y3J9PSQ.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B09Y3J9PSQ"
  },
  {
    "asin": "B0GDY75WHT",
    "name": "Wooden Floor Vase with Brass Work",
    "fullName": "",
    "description": "Add timeless elegance to your living space with this Atreya handcrafted wooden decorative vase, beautifully adorned with intricate brass floral motifs and detailed hand carving. The rich antique brown finish paired with golden brass accents creates a royal, ethnic look that instantly elevates any interior. Perfect as a floor vase, console décor, or statement centerpiece, this tall vase blends traditional craftsmanship with modern home styling.",
    "category": "Home Décor",
    "price": 2699,
    "mrp": 4999,
    "image": "/products/B0GDY75WHT.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B0GDY75WHT"
  },
  {
    "asin": "B09Y29QS4V",
    "name": "White Pearl Beads 6mm — 1000 pcs",
    "fullName": "",
    "description": "6mm ivory pearl beads, 1.5mm hole for jewellery, flower sprays, vines and DIY & wedding craft. Faux/Acrylic/plastic beads For jewelry, wedding lace/dress embellishment, framing and all kinds of craft.",
    "category": "Craft Supplies",
    "price": 199,
    "mrp": 799,
    "image": "/products/B09Y29QS4V.jpg",
    "amazonUrl": "https://www.amazon.in/dp/B09Y29QS4V"
  }
];
